blank_issues_enabled: true
contact_links:
 - name: Ketal Community Support
   url: "https://ketals.online/#/#ketal:ketals.online"
   about: General support questions can be asked here.
 - name: Ketal Security Policy
   url: https://www.ketals.online/security-disclosure-policy/
   about: Learn more about our security disclosure policy.
